spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:appDb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      continue-on-error: false

  h2:
    console:
      enabled: true

server:
  port: 8080
